# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        pgversion:
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19

    env:
      PGVERSION: ${{ matrix.pgversion }}

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install pg
      run: |
        sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -v $PGVERSION -p -i
        sudo -u postgres createuser -s "$USER"

    - name: build
      run: |
        make PROFILE="-Werror"
        sudo -E make install

    - name: test
      run: |
        sudo pg_conftool $PGVERSION main set shared_preload_libraries pgtt
        sudo service postgresql restart
        make installcheck

    - name: show regression diffs
      if: ${{ failure() }}
      run: |
        cat regression.diffs
